export const COMMON_INGREDIENTS: string[] = [
  'All-purpose flour',
  'Almonds',
  'Apple',
  'Avocado',
  'Baking powder',
  'Baking soda',
  'Banana',
  'Basil',
  'Bay leaf',
  'Beef',
  'Bell pepper',
  'Black beans',
  'Black pepper',
  'Blueberries',
  'Bread',
  'Broccoli',
  'Brown rice',
  'Brown sugar',
  'Butter',
  'Canned tomatoes',
  'Carrot',
  'Cayenne pepper',
  'Celery',
  'Cheddar cheese',
  'Cheese',
  'Chicken breast',
  'Chicken stock',
  'Chickpeas',
  'Chili powder',
  'Chocolate chips',
  'Cilantro',
  'Cinnamon',
  'Coconut oil',
  'Coriander',
  'Corn',
  'Cornstarch',
  'Cucumber',
  'Cumin',
  'Egg',
  'Feta cheese',
  'Fish',
  'Flour',
  'Garlic',
  'Ginger',
  'Green beans',
  'Green onion',
  'Ground beef',
  'Honey',
  'Jalapeno',
  'Ketchup',
  'Lemon',
  'Lentils',
  'Lettuce',
  'Lime',
  'Maple syrup',
  'Mayonnaise',
  'Milk',
  'Mushroom',
  'Mustard',
  'Oats',
  'Olive oil',
  'Onion',
  'Orange',
  'Oregano',
  'Paprika',
  'Parmesan cheese',
  'Parsley',
  'Pasta',
  'Peanut butter',
  'Peas',
  'Pepper',
  'Pork',
  'Potato',
  'Quinoa',
  'Red onion',
  'Rice',
  'Rosemary',
  'Salmon',
  'Salt',
  'Shrimp',
  'Soy sauce',
  'Spinach',
  'Strawberries',
  'Sugar',
  'Sweet potato',
  'Thyme',
  'Tofu',
  'Tomato',
  'Tomato paste',
  'Tuna',
  'Turkey',
  'Turmeric',
  'Vanilla extract',
  'Vegetable oil',
  'Vinegar',
  'Walnuts',
  'Water',
  'White rice',
  'Yogurt',
  'Zucchini',
];
